import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const poppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const openSansFont = Open_Sans({
  variable: "--open-Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CMDA National Conference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppinsFont.variable} ${openSansFont.variable} antialiased bg-background`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
